---


- name: Install sshpass package
  yum:
   name: sshpass
   state: present
  tags:
    - backup

- name: Install rsync package
  yum:
   name: rsync
   state: present
  tags:
    - backup



- name: Generating ssh keys
  openssh_keypair:
    path: /root/.ssh/id_rsa
    force: False
  tags:
    - backup


- name: Copy pubkey script
  copy:
    src: pubkey.sh
    dest: /root/pubkey.sh
    owner: root
    group: root
    mode: '0755'
  tags:
    - backup
    - checksum
        
- name: Execute pubkey.sh script.
  command: sh /root/pubkey.sh
  tags:
    - backup
    - script


- name: Ensure a cronjob that runs to backup root dir
  cron:
    name: "backup root dir"
    minute: 0
    hour: 6,00
    job: "sudo rsync -aAXv / --exclude={'/dev/*','/proc/*','/sys/*','/tmp/*','/run/*','/mnt/*','/media/*','/lost+found'} root@10.0.0.237:/opt/mybackup/$HOSTNAME/ > /dev/null"
  tags:
    - backup