---

#--------------------------------------------------------------------------------------------------------
- name: "Changing hostname"
  hostname:
       name: centos6
  tags: 
    - hostname
#------------------------------------------------------------------------------------------------
  
- name: "Updated /etc/hosts"
  lineinfile:
          dest: /etc/hosts
          regexp: '^127\.0\.0\.1[ \t]+localhost'
          line: '127.0.0.1 localhost centos6'
          state: present
  tags:
    - hostname
  #---------------------------------------------------------------------------------------------------------

- name: "Restart network service"
  service:
       name: network
       state: restarted
  tags:
    - hostname
