---

#--------------------------------------------------------------------------------------------------------
- name: "Changing hostname"
  hostname:
       name: test-server.dsi.comm
  tags: 
    - hostname
#------------------------------------------------------------------------------------------------
  
- name: "Updated /etc/hosts"
  lineinfile:
          dest: /etc/hosts
          regexp: '^127\.0\.0\.1[ \t]+localhost'
          line: '127.0.0.1 localhost test-server.dsi.comm'
          state: present
  tags:
    - hostname
  #---------------------------------------------------------------------------------------------------------

- name: "Restart network service"
  service:
       name: network
       state: restarted
  tags:
    - hostname
