---
#Variables for ec2 creation
aws_access_key: AKIA4WBWLUQ4EIHKDWJT 
aws_secret_key: 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
InstanceType: t2.micro
KeyPair: mykeys
image: ami-00c03f7f7f2ec15c3
region: us-east-2
group: default
SubId: subnet-59b5e623
DeviceName: /dev/xvdb
DeviceType: gp2


export InstanceIds=("i-0a98a5e7c35fd0fc5")
export AWS_PROFILE=aakinlofa