---


#- include: epel.yml

#-----------------------------------------------------------------------------------------------------------------------------

- name: Ensure that timezone is set to UTC
  file: 
    src: /usr/share/zoneinfo/UTC
    dest: /etc/localtime
    state: link
    force: yes
  tags:
    - general
#--------------------------------------------------------------------------------------------- 
- name: Ensure that rsyslog does not follow traditional timestamp, but ISO8601 format
  replace: 
    dest: /etc/rsyslog.conf
    regexp: '^\$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'
    replace: '#$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'
    backup: yes
  tags:
    - general
#------------------------------------------------------------------------------------------
- name: Restart rsyslog for ISO8601 timestamp to take effect
  service:
    name: rsyslog
    state: restarted
    enabled: yes
  tags:
    - general
#-----------------------------------------------------------------------------------------------
- name: Install ntp 
  yum: 
    name: [ ntp ]
    state: present
  register: ntpinstall
  tags:
    - general

#-----------------------------------------------------------------------------------------------
- name: Start the ntp service
  service: 
    name: ntpd
    state: restarted
    enabled: yes
  tags:
    - general
 #--------------------------------------------------------------------------------------------------
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags:
    - general
#------------------------------------------------------------------------------------------------------

- name: Install Tools & Utilities (non development ones)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - httpd
      - git
      - vim
      - lsof
      - tree
      - wget
      - htop
      - git

  tags:
    - general
    - test



- name: Install Tools & Utilities (non development ones)
  yum:
    name: [
     jq,
     tmux,
     lsof,
     dos2unix,
     unix2dos,
     tree,
     wget,
     lz4,
     curl,
     rsync,
     iptraf,
     telnet,
     nc,
     tcpdump,
     ltrace,
     strace,
     iftop,
     pv,
     git,
     logrotate
    ]    
    state: installed
    enablerepo: epel
  tags:
    - general
#--------------------------------------------------------------------------------------------------------

- name: Copy config files
  copy:
    src: etc/issue.net
    dest: /etc/
  tags:
    - general
    - banner

- name: Add warning banner to sshd_config
  lineinfile:
     dest: /etc/ssh/sshd_config
     state: present
     regexp: '^Banner '
     line: 'Banner /etc/issue.net'
  register: newconfig
  tags:
    - general
    - banner

- name: Restart sshd service if there is a change in sshd_config file
  service:
    name: sshd
    state: restarted
  when: newconfig.changed
  tags:
    - general
    - banner
